apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: anyxrs.test.fn.upbound.io
spec:
  group: test.fn.upbound.io
  names:
    kind: AnyXR
    plural: anyxrs
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
