---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: upbound-function-pause-when-ready
  annotations:
    # This tells crossplane beta render to connect to the function locally.
    render.crossplane.io/runtime: Development
spec:
  # This is ignored when using the Development runtime.
  package: xpkg.upbound.io/xnull/function-pause-when-ready:v0.1.2
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: upbound-function-patch-and-transform
spec:
  package: xpkg.upbound.io/upbound/function-patch-and-transform:v0.2.1
